In [1]:
import numpy as np
import pandas as pd
import json
import os

In [2]:
df_2016_1 = pd.read_csv('/kaggle/input/petavue-data/2016_original/2016/On_Time_On_Time_Performance_2016_1/On_Time_On_Time_Performance_2016_1.csv')
df_2016_2 = pd.read_csv('/kaggle/input/petavue-data/2016_original/2016/On_Time_On_Time_Performance_2016_2/On_Time_On_Time_Performance_2016_2.csv')
df_2016_3 = pd.read_csv('/kaggle/input/petavue-data/2016_original/2016/On_Time_On_Time_Performance_2016_3/On_Time_On_Time_Performance_2016_3.csv')
df_2016_4 = pd.read_csv('/kaggle/input/petavue-data/2016_original/2016/On_Time_On_Time_Performance_2016_4/On_Time_On_Time_Performance_2016_4.csv')
df_2016_5 = pd.read_csv('/kaggle/input/petavue-data/2016_original/2016/On_Time_On_Time_Performance_2016_5/On_Time_On_Time_Performance_2016_5.csv')
df_2016_6 = pd.read_csv('/kaggle/input/petavue-data/2016_original/2016/On_Time_On_Time_Performance_2016_6/On_Time_On_Time_Performance_2016_6.csv')
df_2016_7 = pd.read_csv('/kaggle/input/petavue-data/2016_original/2016/On_Time_On_Time_Performance_2016_7/On_Time_On_Time_Performance_2016_7.csv')
df_2016_8 = pd.read_csv('/kaggle/input/petavue-data/2016_original/2016/On_Time_On_Time_Performance_2016_8/On_Time_On_Time_Performance_2016_8.csv')
df_2016_9 = pd.read_csv('/kaggle/input/petavue-data/2016_original/2016/On_Time_On_Time_Performance_2016_9/On_Time_On_Time_Performance_2016_9.csv')
df_2016_10 = pd.read_csv('/kaggle/input/petavue-data/2016_original/2016/On_Time_On_Time_Performance_2016_10/On_Time_On_Time_Performance_2016_10.csv')
df_2016_11 = pd.read_csv('/kaggle/input/petavue-data/2016_original/2016/On_Time_On_Time_Performance_2016_11/On_Time_On_Time_Performance_2016_11.csv')
df_2016_12 = pd.read_csv('/kaggle/input/petavue-data/2016_original/2016/On_Time_On_Time_Performance_2016_12/On_Time_On_Time_Performance_2016_12.csv')

/tmp/ipykernel_42/4119604408.py:1: DtypeWarning: Columns (77) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2016_1 = pd.read_csv('/kaggle/input/petavue-data/2016_original/2016/On_Time_On_Time_Performance_2016_1/On_Time_On_Time_Performance_2016_1.csv')
/tmp/ipykernel_42/4119604408.py:2: DtypeWarning: Columns (77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2016_2 = pd.read_csv('/kaggle/input/petavue-data/2016_original/2016/On_Time_On_Time_Performance_2016_2/On_Time_On_Time_Performance_2016_2.csv')
/tmp/ipykernel_42/4119604408.py:3: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2016_3 = pd.read_csv('/kaggle/input/petavue-data/2016_original/2016/On_Time_On_Time_Performance_2016_3/On_Time_On_Time_Performance_2016_3.csv')
/tmp/ipykernel_42/4119604408.py:4: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2016_4 = pd.read_csv('/kaggle/input/petavue-data/2016_original/2016/On_Time_On_Time_Performance_2016_4/On_Time_On_Time_Performance_2016_4.csv')
/tmp/ipykernel_42/4119604408.py:5: DtypeWarning: Columns (48,77,84,85) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2016_5 = pd.read_csv('/kaggle/input/petavue-data/2016_original/2016/On_Time_On_Time_Performance_2016_5/On_Time_On_Time_Performance_2016_5.csv')
/tmp/ipykernel_42/4119604408.py:6: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2016_6 = pd.read_csv('/kaggle/input/petavue-data/2016_original/2016/On_Time_On_Time_Performance_2016_6/On_Time_On_Time_Performance_2016_6.csv')
/tmp/ipykernel_42/4119604408.py:7: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2016_7 = pd.read_csv('/kaggle/input/petavue-data/2016_original/2016/On_Time_On_Time_Performance_2016_7/On_Time_On_Time_Performance_2016_7.csv')
/tmp/ipykernel_42/4119604408.py:8: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2016_8 = pd.read_csv('/kaggle/input/petavue-data/2016_original/2016/On_Time_On_Time_Performance_2016_8/On_Time_On_Time_Performance_2016_8.csv')
/tmp/ipykernel_42/4119604408.py:9: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2016_9 = pd.read_csv('/kaggle/input/petavue-data/2016_original/2016/On_Time_On_Time_Performance_2016_9/On_Time_On_Time_Performance_2016_9.csv')
/tmp/ipykernel_42/4119604408.py:10: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2016_10 = pd.read_csv('/kaggle/input/petavue-data/2016_original/2016/On_Time_On_Time_Performance_2016_10/On_Time_On_Time_Performance_2016_10.csv')
/tmp/ipykernel_42/4119604408.py:11: DtypeWarning: Columns (48,69,76,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2016_11 = pd.read_csv('/kaggle/input/petavue-data/2016_original/2016/On_Time_On_Time_Performance_2016_11/On_Time_On_Time_Performance_2016_11.csv')
/tmp/ipykernel_42/4119604408.py:12: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2016_12 = pd.read_csv('/kaggle/input/petavue-data/2016_original/2016/On_Time_On_Time_Performance_2016_12/On_Time_On_Time_Performance_2016_12.csv')

In [3]:
df_2016 = pd.concat([df_2016_1, df_2016_2, df_2016_3, df_2016_4, df_2016_5, df_2016_6, df_2016_7, df_2016_8, df_2016_9, df_2016_10, df_2016_11, df_2016_12])

In [4]:
df_2016.shape

(5617658, 110)

In [5]:
df_2016.columns

Index(['Year', 'Quarter', 'Month', 'DayofMonth', 'DayOfWeek', 'FlightDate',
       'UniqueCarrier', 'AirlineID', 'Carrier', 'TailNum',
       ...
       'Div4TailNum', 'Div5Airport', 'Div5AirportID', 'Div5AirportSeqID',
       'Div5WheelsOn', 'Div5TotalGTime', 'Div5LongestGTime', 'Div5WheelsOff',
       'Div5TailNum', 'Unnamed: 109'],
      dtype='object', length=110)

In [6]:
df_2017_1 = pd.read_csv('/kaggle/input/petavue-data/2017_original/2017/On_Time_On_Time_Performance_2017_1/On_Time_On_Time_Performance_2017_1.csv')
df_2017_2 = pd.read_csv('/kaggle/input/petavue-data/2017_original/2017/On_Time_On_Time_Performance_2017_2/On_Time_On_Time_Performance_2017_2.csv')
df_2017_3 = pd.read_csv('/kaggle/input/petavue-data/2017_original/2017/On_Time_On_Time_Performance_2017_3/On_Time_On_Time_Performance_2017_3.csv')
df_2017_4 = pd.read_csv('/kaggle/input/petavue-data/2017_original/2017/On_Time_On_Time_Performance_2017_4/On_Time_On_Time_Performance_2017_4.csv')
df_2017_5 = pd.read_csv('/kaggle/input/petavue-data/2017_original/2017/On_Time_On_Time_Performance_2017_5/On_Time_On_Time_Performance_2017_5.csv')
df_2017_6 = pd.read_csv('/kaggle/input/petavue-data/2017_original/2017/On_Time_On_Time_Performance_2017_6/On_Time_On_Time_Performance_2017_6.csv')
df_2017_7 = pd.read_csv('/kaggle/input/petavue-data/2017_original/2017/On_Time_On_Time_Performance_2017_7/On_Time_On_Time_Performance_2017_7.csv')
df_2017_8 = pd.read_csv('/kaggle/input/petavue-data/2017_original/2017/On_Time_On_Time_Performance_2017_8/On_Time_On_Time_Performance_2017_8.csv')
df_2017_9 = pd.read_csv('/kaggle/input/petavue-data/2017_original/2017/On_Time_On_Time_Performance_2017_9/On_Time_On_Time_Performance_2017_9.csv')
df_2017_10 = pd.read_csv('/kaggle/input/petavue-data/2017_original/2017/On_Time_On_Time_Performance_2017_10/On_Time_On_Time_Performance_2017_10.csv')
df_2017_11 = pd.read_csv('/kaggle/input/petavue-data/2017_original/2017/On_Time_On_Time_Performance_2017_11/On_Time_On_Time_Performance_2017_11.csv')
df_2017_12 = pd.read_csv('/kaggle/input/petavue-data/2017_original/2017/On_Time_On_Time_Performance_2017_12/On_Time_On_Time_Performance_2017_12.csv')

/tmp/ipykernel_42/880316883.py:1: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2017_1 = pd.read_csv('/kaggle/input/petavue-data/2017_original/2017/On_Time_On_Time_Performance_2017_1/On_Time_On_Time_Performance_2017_1.csv')
/tmp/ipykernel_42/880316883.py:2: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2017_2 = pd.read_csv('/kaggle/input/petavue-data/2017_original/2017/On_Time_On_Time_Performance_2017_2/On_Time_On_Time_Performance_2017_2.csv')
/tmp/ipykernel_42/880316883.py:3: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2017_3 = pd.read_csv('/kaggle/input/petavue-data/2017_original/2017/On_Time_On_Time_Performance_2017_3/On_Time_On_Time_Performance_2017_3.csv')
/tmp/ipykernel_42/880316883.py:4: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2017_4 = pd.read_csv('/kaggle/input/petavue-data/2017_original/2017/On_Time_On_Time_Performance_2017_4/On_Time_On_Time_Performance_2017_4.csv')
/tmp/ipykernel_42/880316883.py:5: DtypeWarning: Columns (48,77) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2017_5 = pd.read_csv('/kaggle/input/petavue-data/2017_original/2017/On_Time_On_Time_Performance_2017_5/On_Time_On_Time_Performance_2017_5.csv')
/tmp/ipykernel_42/880316883.py:6: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2017_6 = pd.read_csv('/kaggle/input/petavue-data/2017_original/2017/On_Time_On_Time_Performance_2017_6/On_Time_On_Time_Performance_2017_6.csv')
/tmp/ipykernel_42/880316883.py:7: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2017_7 = pd.read_csv('/kaggle/input/petavue-data/2017_original/2017/On_Time_On_Time_Performance_2017_7/On_Time_On_Time_Performance_2017_7.csv')
/tmp/ipykernel_42/880316883.py:8: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2017_8 = pd.read_csv('/kaggle/input/petavue-data/2017_original/2017/On_Time_On_Time_Performance_2017_8/On_Time_On_Time_Performance_2017_8.csv')
/tmp/ipykernel_42/880316883.py:9: DtypeWarning: Columns (77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2017_9 = pd.read_csv('/kaggle/input/petavue-data/2017_original/2017/On_Time_On_Time_Performance_2017_9/On_Time_On_Time_Performance_2017_9.csv')
/tmp/ipykernel_42/880316883.py:10: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2017_10 = pd.read_csv('/kaggle/input/petavue-data/2017_original/2017/On_Time_On_Time_Performance_2017_10/On_Time_On_Time_Performance_2017_10.csv')
/tmp/ipykernel_42/880316883.py:11: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2017_11 = pd.read_csv('/kaggle/input/petavue-data/2017_original/2017/On_Time_On_Time_Performance_2017_11/On_Time_On_Time_Performance_2017_11.csv')
/tmp/ipykernel_42/880316883.py:12: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2017_12 = pd.read_csv('/kaggle/input/petavue-data/2017_original/2017/On_Time_On_Time_Performance_2017_12/On_Time_On_Time_Performance_2017_12.csv')

In [7]:
df_2017 = pd.concat([df_2017_1, df_2017_2, df_2017_3, df_2017_4, df_2017_5, df_2017_6, df_2017_7, df_2017_8, df_2017_9, df_2017_10, df_2017_11, df_2017_12])

In [8]:
df_2017.shape

(5674621, 110)

In [9]:
df_2017.columns

Index(['Year', 'Quarter', 'Month', 'DayofMonth', 'DayOfWeek', 'FlightDate',
       'UniqueCarrier', 'AirlineID', 'Carrier', 'TailNum',
       ...
       'Div4TailNum', 'Div5Airport', 'Div5AirportID', 'Div5AirportSeqID',
       'Div5WheelsOn', 'Div5TotalGTime', 'Div5LongestGTime', 'Div5WheelsOff',
       'Div5TailNum', 'Unnamed: 109'],
      dtype='object', length=110)

In [10]:
### Checking the number of unique codes used in the entire 2016 dataset
df_2016['Origin'].nunique()

313

In [11]:
### Creating a list of the relevant 15 airport codes
airport_codes = ['ATL', 'CLT', 'DEN', 'DFW', 'EWR', 'IAH', 'JFK', 'LAS', 'MCO', 'MIA', 'ORD', 'PHX', 'SEA', 'SFO']

In [12]:
### Only keep the rows which have origin and destination from the relavant airports
df_2016_airport = df_2016[df_2016['Origin'].isin(airport_codes) & df_2016['Dest'].isin(airport_codes)]

In [13]:
### Do the same for 2017
df_2017_airport = df_2017[df_2017['Origin'].isin(airport_codes) & df_2017['Dest'].isin(airport_codes)]

In [14]:
print(df_2016_airport.shape)
print(df_2017_airport.shape)

(733332, 110)
(719149, 110)

In [15]:
### Combined the 2016 and 2017 data into 1 dataframe
df_2016_17 = pd.concat([df_2016_airport, df_2017_airport])

In [16]:
### Make a list of desired columns from the flight dataset
desired_columns = ['FlightDate', 'Quarter', 'Year', 'Month', 'DayofMonth', 'DepTime', 'DepDel15', 'CRSDepTime', 'DepDelayMinutes', 'Origin', 'Dest', 'ArrTime', 'CRSArrTime', 'ArrDel15', 'ArrDelayMinutes']

In [49]:
df_2016_17_filtered = df_2016_17[desired_columns]

In [50]:
df_2016_17_filtered.columns

Index(['FlightDate', 'Quarter', 'Year', 'Month', 'DayofMonth', 'DepTime',
       'DepDel15', 'CRSDepTime', 'DepDelayMinutes', 'Origin', 'Dest',
       'ArrTime', 'CRSArrTime', 'ArrDel15', 'ArrDelayMinutes'],
      dtype='object')

In [59]:
df_2016_17_filtered['FlightDate'] = pd.to_datetime(df_2016_17_filtered['FlightDate'])

# Convert ArrTime column to datetime format
df_2016_17_filtered['ArrTime_new'] = pd.to_datetime(df_2016_17_filtered['ArrTime'], format='%H%M', errors='coerce')

# Create a new column arrival_time by rounding off the ArrTime to the nearest hour
df_2016_17_filtered['arrival_time'] = df_2016_17_filtered['ArrTime_new'].dt.round('H').dt.strftime('%H%M')

# Create a new column arrival_date using the FlightDate
df_2016_17_filtered['arrival_date'] = df_2016_17_filtered['FlightDate'].dt.strftime('%Y-%m-%d')

/tmp/ipykernel_42/535729627.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2016_17_filtered['FlightDate'] = pd.to_datetime(df_2016_17_filtered['FlightDate'])
/tmp/ipykernel_42/535729627.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2016_17_filtered['ArrTime_new'] = pd.to_datetime(df_2016_17_filtered['ArrTime'], format='%H%M', errors='coerce')
/tmp/ipykernel_42/535729627.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2016_17_filtered['arrival_time'] = df_2016_17_filtered['ArrTime_new'].dt.round('H').dt.strftime('%H%M')
/tmp/ipykernel_42/535729627.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2016_17_filtered['arrival_date'] = df_2016_17_filtered['FlightDate'].dt.strftime('%Y-%m-%d')

In [52]:
df_2016_17_filtered[['FlightDate', 'DepTime', 'ArrTime', 'arrival_time', 'arrival_date']].head()

   FlightDate  DepTime  ArrTime arrival_time arrival_date
57 2016-01-01    741.0   1610.0         1600   2016-01-01
58 2016-01-02    737.0   1613.0         1600   2016-01-02
59 2016-01-03    743.0   1547.0         1600   2016-01-03
60 2016-01-04    737.0   1551.0         1600   2016-01-04
61 2016-01-05    708.0   1524.0         1500   2016-01-05

In [21]:
#### The flight side of dataset is prepared, lets move to the weather dataset which is in json

In [22]:
airport_codes

['ATL',
 'CLT',
 'DEN',
 'DFW',
 'EWR',
 'IAH',
 'JFK',
 'LAS',
 'MCO',
 'MIA',
 'ORD',
 'PHX',
 'SEA',
 'SFO']

In [23]:
# def create_dataframe_from_json(json_object):
#     hourly_data_list = []

#     for daily_entry in json_object['data']['weather']:
#         date = daily_entry['date']
        
#         for hourly_entry in daily_entry['hourly']:
#             hourly_data = {
#                 'WindSpeedKmph': hourly_entry['windspeedKmph'],
#                 'WindDirDegree': hourly_entry['winddirDegree'],
#                 'WeatherCode': hourly_entry['weatherCode'],
#                 'precipMM': hourly_entry['precipMM'],
#                 'Visibility': hourly_entry['visibility'],
#                 'Pressure': hourly_entry['pressure'],
#                 'Cloudcover': hourly_entry['cloudcover'],
#                 'DewPointF': hourly_entry['DewPointF'],
#                 'WindGustKmph': hourly_entry['WindGustKmph'],
#                 'tempF': hourly_entry['tempF'],
#                 'WindChillF': hourly_entry['WindChillF'],
#                 'Humidity': hourly_entry['humidity'],
#                 'date': date,
#                 'time': hourly_entry['time'],
#                 'country' : 'ATL'
#             }
            
#             hourly_data_list.append(hourly_data)

#     # Creating a DataFrame from the list of dictionaries
#     df = pd.DataFrame(hourly_data_list)
    
#     return df

In [24]:
# w2016_1 = json.loads(open('/kaggle/input/petavue-data/ATL-20240114T114025Z-001/ATL/2016-1.json').read())
# df1 = create_dataframe_from_json(w2016_1)
# w2016_2 = json.loads(open('/kaggle/input/petavue-data/ATL-20240114T114025Z-001/ATL/2016-2.json').read())
# df2 = create_dataframe_from_json(w2016_2)
# w2016_3 = json.loads(open('/kaggle/input/petavue-data/ATL-20240114T114025Z-001/ATL/2016-3.json').read())
# df3 = create_dataframe_from_json(w2016_3)
# w2016_4 = json.loads(open('/kaggle/input/petavue-data/ATL-20240114T114025Z-001/ATL/2016-4.json').read())
# df4 = create_dataframe_from_json(w2016_4)
# w2016_5 = json.loads(open('/kaggle/input/petavue-data/ATL-20240114T114025Z-001/ATL/2016-5.json').read())
# df5 = create_dataframe_from_json(w2016_5)
# w2016_6 = json.loads(open('/kaggle/input/petavue-data/ATL-20240114T114025Z-001/ATL/2016-6.json').read())
# df6 = create_dataframe_from_json(w2016_6)
# w2016_7 = json.loads(open('/kaggle/input/petavue-data/ATL-20240114T114025Z-001/ATL/2016-7.json').read())
# df7 = create_dataframe_from_json(w2016_7)
# w2016_8 = json.loads(open('/kaggle/input/petavue-data/ATL-20240114T114025Z-001/ATL/2016-8.json').read())
# df8 = create_dataframe_from_json(w2016_8)
# w2016_9 = json.loads(open('/kaggle/input/petavue-data/ATL-20240114T114025Z-001/ATL/2016-9.json').read())
# df9 = create_dataframe_from_json(w2016_9)
# w2016_10 = json.loads(open('/kaggle/input/petavue-data/ATL-20240114T114025Z-001/ATL/2016-10.json').read())
# df10 = create_dataframe_from_json(w2016_10)
# w2016_11 = json.loads(open('/kaggle/input/petavue-data/ATL-20240114T114025Z-001/ATL/2016-11.json').read())
# df11 = create_dataframe_from_json(w2016_11)
# w2016_12 = json.loads(open('/kaggle/input/petavue-data/ATL-20240114T114025Z-001/ATL/2016-12.json').read())
# df12 = create_dataframe_from_json(w2016_12)
# w2017_1 = json.loads(open('/kaggle/input/petavue-data/ATL-20240114T114025Z-001/ATL/2017-1.json').read())
# df13 = create_dataframe_from_json(w2017_1)
# w2017_2 = json.loads(open('/kaggle/input/petavue-data/ATL-20240114T114025Z-001/ATL/2017-2.json').read())
# df14 = create_dataframe_from_json(w2017_2)
# w2017_3 = json.loads(open('/kaggle/input/petavue-data/ATL-20240114T114025Z-001/ATL/2017-3.json').read())
# df15 = create_dataframe_from_json(w2017_3)
# w2017_4 = json.loads(open('/kaggle/input/petavue-data/ATL-20240114T114025Z-001/ATL/2017-4.json').read())
# df16 = create_dataframe_from_json(w2017_4)
# w2017_5 = json.loads(open('/kaggle/input/petavue-data/ATL-20240114T114025Z-001/ATL/2017-5.json').read())
# df17 = create_dataframe_from_json(w2017_5)
# w2017_6 = json.loads(open('/kaggle/input/petavue-data/ATL-20240114T114025Z-001/ATL/2017-6.json').read())
# df18 = create_dataframe_from_json(w2017_6)
# w2017_7 = json.loads(open('/kaggle/input/petavue-data/ATL-20240114T114025Z-001/ATL/2017-7.json').read())
# df19 = create_dataframe_from_json(w2017_7)
# w2017_8 = json.loads(open('/kaggle/input/petavue-data/ATL-20240114T114025Z-001/ATL/2017-8.json').read())
# df20 = create_dataframe_from_json(w2017_8)
# w2017_9 = json.loads(open('/kaggle/input/petavue-data/ATL-20240114T114025Z-001/ATL/2017-9.json').read())
# df21 = create_dataframe_from_json(w2017_9)
# w2017_10 = json.loads(open('/kaggle/input/petavue-data/ATL-20240114T114025Z-001/ATL/2017-10.json').read())
# df22 = create_dataframe_from_json(w2017_10)
# w2017_11 = json.loads(open('/kaggle/input/petavue-data/ATL-20240114T114025Z-001/ATL/2017-11.json').read())
# df23 = create_dataframe_from_json(w2017_11)
# w2017_12 = json.loads(open('/kaggle/input/petavue-data/ATL-20240114T114025Z-001/ATL/2017-12.json').read())
# df24 = create_dataframe_from_json(w2017_12)

# atl = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12, df13, df14, df15, df16, df17, df18, df19, df20, df21, df22, df23, df24])

In [26]:
# atl.shape

In [27]:
def create_dataframe_from_file(json_filepath):
    json_data = json.loads(open(json_filepath).read())
    return create_dataframe_from_json(json_data)

def load_and_concatenate_data(directory_path, airport_codes):
    dfs = []
    
    for airport_code in airport_codes:
        for year in range(2016, 2018):
            for month in range(1, 13):
                json_filename = f'{airport_code}-001/{airport_code}/{year}-{month}.json'
                json_filepath = os.path.join(directory_path, json_filename)

                if os.path.exists(json_filepath):
#                     print(f"Loading {json_filepath}")
                    df = create_dataframe_from_file(json_filepath)
                    df['airport'] = airport_code
                    dfs.append(df)
                else:
                    print(f"File not found: {json_filepath}")

    if not dfs:
        print("No DataFrames to concatenate.")

    concatenated_df = pd.concat(dfs, ignore_index=True)
    return concatenated_df

def create_dataframe_from_json(json_object):
    hourly_data_list = []

    for daily_entry in json_object['data']['weather']:
        date = daily_entry['date']
        
        for hourly_entry in daily_entry['hourly']:
            hourly_data = {
                'WindSpeedKmph': hourly_entry['windspeedKmph'],
                'WindDirDegree': hourly_entry['winddirDegree'],
                'WeatherCode': hourly_entry['weatherCode'],
                'precipMM': hourly_entry['precipMM'],
                'Visibility': hourly_entry['visibility'],
                'Pressure': hourly_entry['pressure'],
                'Cloudcover': hourly_entry['cloudcover'],
                'DewPointF': hourly_entry['DewPointF'],
                'WindGustKmph': hourly_entry['WindGustKmph'],
                'tempF': hourly_entry['tempF'],
                'WindChillF': hourly_entry['WindChillF'],
                'Humidity': hourly_entry['humidity'],
                'date': date,
                'time': hourly_entry['time'],
            }
            
            hourly_data_list.append(hourly_data)

    df = pd.DataFrame(hourly_data_list)
    return df


directory_path = '/kaggle/input/petavue-data1'
airport_codes = ['ATL', 'CLT', 'DEN', 'DFW', 'EWR', 'IAH', 'JFK', 'LAS', 'LAX', 'MCO', 'MIA', 'ORD', 'PHX', 'SEA', 'SFO']

final_df = load_and_concatenate_data(directory_path, airport_codes)

In [28]:
final_df.shape

(263160, 15)

In [29]:
final_df.columns

Index(['WindSpeedKmph', 'WindDirDegree', 'WeatherCode', 'precipMM',
       'Visibility', 'Pressure', 'Cloudcover', 'DewPointF', 'WindGustKmph',
       'tempF', 'WindChillF', 'Humidity', 'date', 'time', 'airport'],
      dtype='object')

In [30]:
final_df['time'].unique()

array(['0', '100', '200', '300', '400', '500', '600', '700', '800', '900',
       '1000', '1100', '1200', '1300', '1400', '1500', '1600', '1700',
       '1800', '1900', '2000', '2100', '2200', '2300'], dtype=object)

In [31]:
### All 15 airports and their data are present
print(final_df['airport'].nunique())  ## 15
print(final_df['date'].nunique())   ### 366 + 365 = 731
#### This shows that all data is covered

15
731

In [60]:
flight = df_2016_17_filtered

In [61]:
flight['arrival_time'] = flight['arrival_time'].astype(str)
flight['arrival_date'] = flight['arrival_date'].astype(str)
flight['Dest'] = flight['Dest'].astype(str)

/tmp/ipykernel_42/3587344657.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  flight['arrival_time'] = flight['arrival_time'].astype(str)
/tmp/ipykernel_42/3587344657.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  flight['arrival_date'] = flight['arrival_date'].astype(str)
/tmp/ipykernel_42/3587344657.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  flight['Dest'] = flight['Dest'].astype(str)

In [34]:
weather = final_df

In [35]:
weather['time'] = weather['time'].astype(str)
weather['date'] = weather['date'].astype(str)
weather['airport'] = weather['airport'].astype(str)

In [62]:
flight.columns

Index(['FlightDate', 'Quarter', 'Year', 'Month', 'DayofMonth', 'DepTime',
       'DepDel15', 'CRSDepTime', 'DepDelayMinutes', 'Origin', 'Dest',
       'ArrTime', 'CRSArrTime', 'ArrDel15', 'ArrDelayMinutes', 'ArrTime_new',
       'arrival_time', 'arrival_date'],
      dtype='object')

In [41]:
weather.columns

Index(['WindSpeedKmph', 'WindDirDegree', 'WeatherCode', 'precipMM',
       'Visibility', 'Pressure', 'Cloudcover', 'DewPointF', 'WindGustKmph',
       'tempF', 'WindChillF', 'Humidity', 'date', 'time', 'airport'],
      dtype='object')

In [63]:
# final_csv = df_2016_17_filtered.merge(final_df, left_on=['arrival_time', 'arrival_date', 'Dest'], right_on=['time', 'date', 'airport'], how='left')
final_csv = flight.merge(weather, left_on=['arrival_time', 'arrival_date', 'Dest'], right_on=['time', 'date', 'airport'], how='left')

In [64]:
flight.shape

(1452481, 18)

In [65]:
final_csv.shape

(1452481, 33)

In [66]:
final_csv.columns

Index(['FlightDate', 'Quarter', 'Year', 'Month', 'DayofMonth', 'DepTime',
       'DepDel15', 'CRSDepTime', 'DepDelayMinutes', 'Origin', 'Dest',
       'ArrTime', 'CRSArrTime', 'ArrDel15', 'ArrDelayMinutes', 'ArrTime_new',
       'arrival_time', 'arrival_date', 'WindSpeedKmph', 'WindDirDegree',
       'WeatherCode', 'precipMM', 'Visibility', 'Pressure', 'Cloudcover',
       'DewPointF', 'WindGustKmph', 'tempF', 'WindChillF', 'Humidity', 'date',
       'time', 'airport'],
      dtype='object')

In [67]:
final_csv[['FlightDate', 'DepTime', 'ArrTime', 'Dest', 'arrival_time', 'arrival_date', 'date', 'time', 'airport']].head()

,FlightDate,DepTime,ArrTime,Dest,arrival_time,arrival_date,date,time,airport
0,2016-01-01,741.0,1610.0,JFK,1600,2016-01-01,2016-01-01,1600,JFK
1,2016-01-02,737.0,1613.0,JFK,1600,2016-01-02,2016-01-02,1600,JFK
2,2016-01-03,743.0,1547.0,JFK,1600,2016-01-03,2016-01-03,1600,JFK
3,2016-01-04,737.0,1551.0,JFK,1600,2016-01-04,2016-01-04,1600,JFK
4,2016-01-05,708.0,1524.0,JFK,1500,2016-01-05,2016-01-05,1500,JFK

In [68]:
final_csv.head()

,FlightDate,Quarter,Year,Month,DayofMonth,DepTime,DepDel15,CRSDepTime,DepDelayMinutes,Origin,...,Pressure,Cloudcover,DewPointF,WindGustKmph,tempF,WindChillF,Humidity,date,time,airport
0,2016-01-01,1,2016,1,1,741.0,0.0,745,0.0,SEA,...,1015,0,32,26,41,32,74,2016-01-01,1600,JFK
1,2016-01-02,1,2016,1,2,737.0,0.0,745,0.0,SEA,...,1016,0,30,23,39,31,71,2016-01-02,1600,JFK
2,2016-01-03,1,2016,1,3,743.0,0.0,745,0.0,SEA,...,1009,46,31,28,40,32,69,2016-01-03,1600,JFK
3,2016-01-04,1,2016,1,4,737.0,0.0,745,0.0,SEA,...,1019,22,15,34,26,11,65,2016-01-04,1600,JFK
4,2016-01-05,1,2016,1,5,708.0,0.0,710,0.0,SEA,...,1035,0,14,19,27,15,61,2016-01-05,1500,JFK